### ISSUE TITLE
please add delete file feature 

### ISSUE THREAD

**Issue by m7ammad7assan** [peterfreeman/ngx-dropzone#15]
I tried to implemet file deletion feature but I could not !

**Comment by peterfreeman** [comment]
Hi there,

thanks for your feedback. I think it would be a useful feature to enable deleting files.
Right now, you're the first one to request it and since I don't have much time for Open Source at the moment, I will delay the implementation for some weeks. 
Make sure to come back when the feature is included. Of course, I would also appreciate a pull request from you.

Happy coding! 🤓

**Comment by peterfreeman** [comment]
I just released v2 of the library which includes this feature. You can try it out.
