### ISSUE TITLE
Preview images for edit before add more.

### ISSUE THREAD

**Issue by myshinjio** [peterfreeman/ngx-dropzone#40]
How to display a default image file from URL?

**Comment by peterfreeman** [comment]
Hi there,

you could download the image data as base64 string and create a `File` object yourself. This object could be used with the `ngx-dropzone-image-preview` component. 

Otherwise you could try to implement a custom preview component as described [here](https://github.com/peterfreeman/ngx-dropzone/wiki/How-to-create-a-custom-preview-component%3F).

Happy coding! 🤓
