### ISSUE TITLE
Change style of ngx-dropzone-preview

### ISSUE THREAD

**Issue by nhgiang196** [peterfreeman/ngx-dropzone#56]
Recent days I have things to do with this ngx-dropzone. I found out these element.style can't be change because it will be automaticolly reverted when I change the value.

![image](https://user-images.githubusercontent.com/22267870/75016013-9cd4d480-54bc-11ea-8365-a1b2129dc16c.png)

Looking for solution for week. 
This [ngx-dropzone-wrapper](https://github.com/zefoy/ngx-dropzone-wrapper)  solved this by using [useDropzoneClass] which is not availble for ngx-dropzone. 

Be kind helping me. Thanks

Edit:
This is my code from *.component.html
![image](https://i.imgur.com/XbkSLxJ.png)

**Comment by nhgiang196** [comment]
I found these lines in source code. Maybe this is an important key. 

![image](https://i.imgur.com/fw8X2fJ.png)

**Comment by r-hannuschka** [comment]
It seems if you want change these styles you have to create and scss file which will override these styles but add an important on every one, since this are inline styles which are directly bound to an element.

And as much i hate that important it seems the only way to do this here.

@example

```scss
...
border-radius: none !important;
...
```

It would be better if this will be a scss class which could be overidden by scss.

**Comment by peterfreeman** [comment]
Hey there,

@r-hannuschka is right here. I decided to implement the styles as part of the `component.ts` so that they would get inherited from the basic preview to the image, video or any custom preview component. If you have a better idea, please let me know. 
For now, it's intended behavior to use the `!important` flag on your custom css.

Happy coding! 🤓

**Comment by j0hnwhyte** [comment]
I'm facing the same problem, putting the style inline seems a bad choice here. Using !important in CSS is strongly discouraged everywhere ~~and feels like using a nuke to clean your house's floor~~

**Comment by Jenifer-Ramsingh** [comment]
I have used this in my css this works for me better. try this out 👍🏻 

:host ::ng-deep img {
  max-width: 100% !important;
}

😇😇😇😇
