### ISSUE TITLE
Option examples

### ISSUE THREAD

**Issue by JarvisStriker** [peterfreeman/ngx-dropzone#63]
It will be easier if you can provide option examples. Suppose if I want to set file size, I need to follow a trial and error approach to find the right values to put in. It will be helpful if you put up few examples for all options

**Comment by juanAFernandez** [comment]
Yeah, I think the same. I put the unit in size in README because I was not very sure about it. And now I finded other problem with accept. In some examples you can see "'image/jpeg,image/jpg,image/png'"; but must be without "" or give an error.

**Comment by ShirinShirinak** [comment]
Yes! examples will be great! I'm trying to have the file type as 'csv' and also turn multiple off so I can only accept 1 file, I use [multiple]="false" and [accept]='csv', I get no errors but the whole thing stops working, I won't be able to drop any files in there any more!

**Comment by peterfreeman** [comment]
Hey guys,

thanks for your feedback. I will update the README when I'm back to this. Trying to do it in the next few weeks.

Happy coding! 🤓

**Comment by juanAFernandez** [comment]
Thanks for your work @peterfreeman :)

**Comment by spectroman** [comment]
well, am having the same problem with [accept], but unlike @juanAFernandez it does not work whatsoever. I have already tried:

`=".jpeg,.png"` (as decribed in: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#attr-accept )
but it appears to not follow a standard at all

`='.jpg,png'` -- won't work

`='image/jpg,/image/png'` -- won't work

doesnt matter if is `"` or `'` or anything else...

yeah well, I will need to deny the files after closing the ngx-dropzone, which is very poor behavior and not desired at all.

I see the that in June 2nd it was promised better examples,  but we are already in November basically... and nothing :(

:-1:

**Comment by spectroman** [comment]
I see the code here:

```
	private isAccepted(file: File, accept: string): boolean {

		if (accept === '*') {
			return true;
		}

		const acceptFiletypes = accept.split(',').map(it => it.toLowerCase().trim());
		const filetype = file.type.toLowerCase();
		const filename = file.name.toLowerCase();

		const matchedFileType = acceptFiletypes.find(acceptFiletype => {

			// check for wildcard mimetype (e.g. image/*)
			if (acceptFiletype.endsWith('/*')) {
				return filetype.split('/')[0] === acceptFiletype.split('/')[0];
			}

			// check for file extension (e.g. .csv)
			if (acceptFiletype.startsWith(".")) {
				return filename.endsWith(acceptFiletype);
			}

			// check for exact mimetype match (e.g. image/jpeg)
			return acceptFiletype == filetype;
		});

		return !!matchedFileType;
	}
```

which would suggest the examples already given in here would allow this option to work, but for some reason, as I am using "angular 10" I have tons of errors for most of these options in here.

`[accept]='.jpg,.png'`
``` error NG5002: Parser Error: Unexpected token . at column 1 in [.jpg,.png]```

**Comment by juanAFernandez** [comment]
About yout thrid example, in my case it works with `'image/jpeg,image/jpg,image/png'`. Have you tried with `='image/jpg,image/png'` (removing \). Which version are you triying?

**Comment by spectroman** [comment]
I have here: `ngx-dropzone-2.2.2`

None of the syntax in here works for me.

**Comment by juanAFernandez** [comment]
This is an extract of my code working well, in the same version as you:
```
 <ngx-dropzone
   accept="'image/jpeg,image/jpg,image/png'">
</ngx-dropzone>
```

**Comment by spectroman** [comment]
Aha LOL

I was blindly following the `[accept]` (as a binding variable), as it appears on the README.., now following your suggestion, I first tried:

`accept="'image/jpeg,image/jpg,image/png'"`
That simply didn't work, with no errors... then I've tried:

`accept="image/jpeg,image/jpg,image/png,image/gif"`
and this is now working!

:+1: @juanAFernandez

**Comment by juanAFernandez** [comment]
Thanks @spectroman . You're right, my example was wrong, (my fault, copy and paste too fast). I'm glad it was help you. :)
I will do a pull request with that asap.

Our tested correct way is: `accept="image/jpeg,image/jpg,image/png,image/gif"` 👍

**Comment by jwienekamp** [comment]
The problem you guys are facing is the way angular handles input bindings. Without square brackets angular interprets the input as a string literal. Thats why your latest examples are working: `accept=".png,.jpg"`. 

But when square brackets are added around the input binding, angular expects a property (dynamic expression) as input. That would look like this `[accept]="variableFromComponent"`, where variableFromComponent is defined as a string property in the component itself:
```javascript
variableFromComponent = '.png,.jpg';
```  
\
Coming back to your problem @spectroman:
> `[accept]='.jpg,.png'`
> ` error NG5002: Parser Error: Unexpected token . at column 1 in [.jpg,.png]`

If you define the input as following `[accept]='.jpg, .png'` angular interprets this as a expression because of the square brackets. Meaning it tries to read a property from the component with the name `.jpg,.png`, what obviously fails. 

When adding square brackets always make sure to enclose the text in a second pair of quotes `[accept]="'.jpg,.png'"` if you want the input to be interpreted as a string literal and not as an expression.

For further information here is a link to the angular guide: [Angular - Property binding](https://angular.io/guide/property-binding#binding-to-a-property)
