### ISSUE TITLE
Not showing added files

### ISSUE THREAD

**Issue by farlock85** [peterfreeman/ngx-dropzone#9]
When I drag a non-image on the component it will fire the onFilesAdded event, but it doesn't show anything visual on the canvas unless it is an image file.

Is this expected behaviour or do I need custom implementation?

**Comment by peterfreeman** [comment]
Hi,

thanks for your feedback.
Currently, this is expected behavior. Only images will be previewed.
If more people request to also view other files, I'll add it to the lib. But for now you're the only one, so you would have to implement this on your own.

Of course, I'd highly appreciate a pull request from you. 🤓
Happy coding!

**Comment by marcantoinecossette** [comment]
I am interested ! It would be so nice

**Comment by cariboufute** [comment]
I would be interested too! Might help you with this if I have the time...

**Comment by johnyang90** [comment]
I am interested too.

**Comment by peterfreeman** [comment]
Hey guys,

With the latest version I added the feature to preview all file types.
Please note that the API changed, so now it's `[showPreviews]` instead of `[showImagePreviews]`.

Check it out and let me know if you like it. 🤓

**Comment by cariboufute** [comment]
Thanks a lot! It works really well!
